@startuml

title Class diagram: ctd_processing

class bl_file.BlFile #DF6ED8 {
	+file_path
	-_number_of_bottles
	number_of_bottles, @p
==
	-_save_number_of_bottles()
}

class bokeh_server.CTDBokehQC #4C2BE8 {
	-_bokeh_server
	-_run_bokeh_server_bat_file
	-_run_bokeh_server_file
	-_run_bokeh_server_template_file
==
	+set_data_directory()
	+start_bokeh_server()
	+stop_bokeh_server()
}

class cnv_column_info.CnvInfoFile #3C860B {
	+file_path
	+file_stem
	+sensor_info
==
	+get_info()
	-__repr__()
	-_load_file()
}

class cnv_column_info.CnvInfoFiles #3C860B {
	+directory
	-_files
	files, @p
==
	+get_info()
	-__repr__()
	-_load_files()
}

class cnv_column_info.CnvSensorInfo #3C860B {
	-_file_path
	file, @p
	name, @p
==
	-__repr__()
}

class cnv_file.CNVfile #C514A0 {
	+cnv_info_object
	+col_dens
	+col_dens2
	+col_depth
	+col_pres
	+col_sv
	+data
	+date_format_in_file
	+file_path
	+g
	+header
	+instrument_number
	+linebreak
	+missing_value
	+missing_value_str
	+nr_data_lines
	+parameters
	+use_cnv_info_format
	-_ctd_files
	-_lat
	-_lon
	-_station
	-_time
	lat, @p
	lon, @p
	station, @p
	time, @p
==
	+modify()
	+save_file()
	-_change_parameter_name()
	-_check_index()
	-_get_calculated_true_depth()
	-_get_data_rows()
	-_get_density_data()
	-_get_depth_data()
	-_get_mean_sound_velocity()
	-_get_parameter_name_matching_string()
	-_get_pressure_data()
	-_get_sound_velocity_data()
	-_load_info()
	-_modify_depth()
	-_modify_fluorescence()
	-_modify_header_information()
	-_modify_irradiance()
	-_modify_span()
	-_save_columns()
	-_set_active_parameters()
}

class cnv_file.CNVfileInfo #C514A0 {
	+date_format_in_file
	-_lat
	-_lon
	-_path
	-_station
	-_time
	lat, @p
	lon, @p
	station, @p
	time, @p
==
	-_get_info_from_file()
}

class cnv_file.CNVfileXML #C7A863 {
	+path
	+tree
	+xmlstring
	serial_number, @p
==
	+get_datetime_object(), @sm
	+get_sensor_info()
	-_get_comment_for_channel()
}

class cnv_header.CNVheader #C89EA8 {
	+linebreak
	+rows
==
	+add_row()
	+append_to_row()
	+get_row_index_for_matching_string()
	+insert_row_after()
	+replace_row()
	+replace_string_at_index()
}

class cnv_parameter.CNVparameter #BD90F3 {
	+active
	+cnv_info_object
	+info
	+name
	+sample_value
	+use_cnv_info_format
	-_data
	-_nr_decimals
	-_tot_value_length
	-_value_format
	data, @p
	format, @p
==
	+add_data()
	+change_name()
	+get_value_as_string_for_index()
	+set_active()
	+set_value_length()
	-__repr__()
	-_set_nr_decimals()
}

class data_delivery.DeliveryMetadataFile #A8D9DE {
	+template_path
	+wb
	-_metadata
	-_metadata_columns
	-_metadata_header_row
	-_metadata_sheet_name
	-_sensorinfo
	-_sensorinfo_columns
	-_sensorinfo_header_row
	-_sensorinfo_sheet_name
==
	+add_delivery_note_from_file()
	+add_metadata_from_file()
	+add_sensorinfo_from_file()
	+old_save_file()
	+old_write_metadata()
	+old_write_sensorinfo()
	+save_file()
	-_copy_template()
	-_get_header_in_worksheet()
	-_load_headers()
	-_write_df_to_xlsx()
	-_write_metadata()
	-_write_sensorinfo()
}

class delivery_note.DeliveryNote #303DFC {
	-_comment
	-_contact
	-_data
	-_description
	-_directory
	-_paths
	-_save_path
	-_stem
==
	+write_to_file()
	-__str__()
	-_save_info()
}

class derive.DerivePSAfile #1CF267 {
	
==
	+set_tau_correction()
	+turn_tau_correction_off()
	+turn_tau_correction_on()
}

class file_handler.File #7B21EA {
	+path
	name, @p
	suffix, @p
==
	-__call__()
	-__eq__()
	-__str__()
}

class file_handler.SBEFileHandler #7B21EA {
	+local_files
	+paths
	+server_files
==
	+copy_files_to_server()
	+get_local_file_path()
	+not_on_server()
	+not_updated_on_server()
	+select_file()
	-_load_files()
	-_load_local_files()
	-_load_server_files()
	-_not_on_server()
	-_not_updated_on_server()
}

class file_pattern_nodc.NODCSBECTDFiles #FCDAEB {
	+name, @ca
	+pattern, @ca
	+pattern_example, @ca
	config_file_suffix, @p
	instrument_number, @p
	serno, @p
	shipcode, @p
==
	-_get_proper_file_stem()
}

class file_pattern_old_processing_script.OldSBECTDFiles #5EF571 {
	+name, @ca
	+pattern, @ca
	+pattern_example, @ca
	config_file_suffix, @p
	instrument_number, @p
	serno, @p
	shipcode, @p
==
	-_get_proper_file_stem()
}

class hdr_file.HdrFile #62E562 {
	+date_format_in_file
	+file_path
	-_cruise_number
	-_station
	-_time
	cruise_number, @p
	station, @p
	time, @p
==
	-_get_info_from_file()
}

class instrument_file.InstrumentFile #8CD98C {
	-_info
	-_path
	-_sheets
	-_wb
==
	+get_info_for_parameter_and_sensor_id()
	-__str__()
	-_add_cnv_code_to_pars()
	-_save_info()
}

class loopedit.LoopeditPSAfile #73D5D7 {
	depth, @p
==
	
}

class metadata.MetadataFile #D91E71 {
	-_data
	-_directory
	-_paths
	-_save_path
	-_stem
==
	+write_to_file()
	-__str__()
	-_save_info()
}

class metadata.MetadataRow #D91E71 {
	-_metadata
	-_metadata_columns
	-_path
==
	+get_info()
	+get_metadata_row_from_cnv_file()
	-_save_metadata()
}

class modify.ModifyCTDfiles #1D0AB7 {
	
==
	-_modify_and_save_cnv_file()
}

class param_reported.ParamReported #8347DA {
	+cnv_file_path
	+cnv_reported_names
	+instrument_file
==
	+get_reported_name()
	-_parameter_is_sensor_1(), @sm
	-_parameter_is_sensor_2(), @sm
	-_reported_name_is_sensor_1(), @sm
	-_reported_name_is_sensor_2(), @sm
	-_reported_name_matches_cnv_code(), @sm
}

class parent_abc_class.CTDFiles #00D912 {
	-__proper_pattern, @ca
	-_file_name_info
	-_file_name_info, @ca
	-_files
	-_files, @ca
	-_original_file_path
	-_original_file_path, @ca
	-_plot_files, @ca
	all_files, @p
	parent, @p
	plot_files, @p
	proper_stem, @p
	stem, @p
	tractmethod, @p
==
	+add_processed_file_paths()
	+file_path()
	+has_file()
	+instrument_number()
	+is_valid()
	+lat()
	+lon()
	+modify_and_save_cnv_file()
	+name()
	+pattern()
	+pattern_example()
	+raw_files_extensions()
	+rename_files()
	+serno()
	+set_file_path()
	+shipcode()
	+station()
	+time()
	+year()
	-__call__()
	-__repr__()
	-__str__()
	-_check_file_stem()
	-_get_proper_file_stem()
	-_modify_and_save_cnv_file()
	-_rename_file()
	-_save_file_paths()
}

class paths.SBEPaths #7EC865 {
	-_paths
	-_sub_dir_list_local
	-_sub_dir_list_server
	-_year
	local_sub_directories, @p
	server_sub_directories, @p
	year, @p
==
	+create_local_paths()
	+create_server_paths()
	+get_local_directory()
	+get_path()
	+get_server_directory()
	+set_config_root_directory()
	+set_local_root_directory()
	+set_server_root_directory()
	+set_year()
	-__call__()
	-_get_server_directory_for_year()
	-_local_key()
	-_server_key()
}

class psa_file.PSAfile #6EA8EB {
	+file_path
	+tree
==
	+list_all()
	+save()
	-_get_element_from_tag_list()
	-_get_from_tag_list()
	-_get_value_list()
	-_has_condition()
	-_set_from_tag_list()
}

class psa_file_with_plot.PSAfileWithPlot #E2BDE1 {
	+blueprint_display_parameter_tags
	+display_depth_tags
	+display_nr_bins_tags
	+display_nr_minor_bins_tags
	+display_parameter_tags
	+parameter_max_tag
	+parameter_min_tag
	display_depth, @p
	nr_bins, @p
==
	+get_displayed_parameters()
	+get_parameter_range()
	+set_parameter_range()
	-_get_tag_list_for_parameter()
}

class psa_plot_file.PlotPSAfile #387859 {
	+blueprint_display_parameter_tags
	+display_depth_tags
	+display_parameter_tags
	+parameter_max_tag
	+parameter_min_tag
	+title_tags
	title, @p
==
	
}

class sbe_batch_file.SBEBatchFile #37A71F {
	-_paths
	-_processing_paths
==
	+create_file()
	+run_file()
}

class sbe_parent_class.SBECTDFiles #307904 {
	+raw_files_extensions, @ca
	-_plot_files
	file_path, @p
	lat, @p
	lon, @p
	number_of_bottles, @p
	station, @p
	time, @p
	tractmethod, @p
	year, @p
==
	+add_processed_file_paths()
	+config_file_suffix()
	-_add_local_cnv_file_path()
	-_check_hdr_file()
}

class sbe_processing.SBEProcessing #0A4CE9 {
	-_batch_file
	-_confirmed
	-_ctd_files
	-_file_path
	-_overwrite
	-_paths
	-_processing_paths
	-_setup_file
	platform, @p
	year, @p
==
	+confirm_file()
	+create_sensorinfo_file()
	+get_file_names_in_server_directory()
	+get_platform_options()
	+get_surfacesoak_options()
	+run_process()
	+select_file()
	+set_platform()
	+set_surfacesoak()
	+set_tau_state()
	-_copy_all_files_with_same_file_stem_to_working_dir()
	-_copy_cnv_files_to_local()
	-_copy_file()
	-_copy_plot_files_to_local()
	-_copy_processed_files_to_local()
	-_copy_raw_files_to_local()
	-_get_derive_psa_obj()
}

class sbe_processing_paths.SBEProcessingPaths #5EC794 {
	+sbe_paths
	-_loopedit_paths
	-_new_file_stem
	-_paths
	-_platform
	-_platform_paths
	-_psa_names
	loopedit_paths, @p
	platform, @p
	platforms, @p
==
	+set_config_suffix()
	+set_loopedit()
	+set_raw_file_path()
	+update_paths()
	-__call__()
	-__repr__()
	-__str__()
	-_build_cnv_file_paths_with_new_file_stem()
	-_build_loopedit_file_paths()
	-_build_psa_file_paths()
	-_build_raw_file_paths_with_new_file_stem()
	-_get_all_psa_paths()
	-_get_paths_in_directory(), @sm
	-_save_platform_paths()
}

class sbe_setup_file.SBESetupFile #F3A90F {
	-_ctd_files
	-_paths
	-_proc_paths
==
	+create_file()
	-_add_station_name_to_plots()
	-_get_bottle_sum_line()
	-_get_lines()
	-_write_lines()
}

class seasave.SeasavePSAfile #C68138 {
	+add_samp_tags
	+blueprint_display_parameter_tags
	+cruise_tags
	+data_file_tags
	+display_depth_tags
	+display_nr_bins_tags
	+display_nr_minor_bins_tags
	+display_parameter_tags
	+event_id_tags
	+lat_tags
	+lon_tags
	+metadata_admin_tags
	+metadata_conditions_tags
	+operator_tags
	+parameter_max_tag
	+parameter_min_tag
	+parent_event_id_tags
	+ship_tags
	+station_tags
	+xmlcon_name_tags
	add_samp, @p
	cruise, @p
	data_path, @p
	event_id, @p
	metadata_admin, @p
	metadata_conditions, @p
	operator, @p
	parent_event_id, @p
	position, @p
	ship, @p
	station, @p
	xmlcon_path, @p
==
	
}

class sensor_info_file.SensorInfoFile #8E00A6 {
	+cnv_info
	+instrument_file
	-_data
	-_save_path
	-_stem
==
	+create_file_from_cnv_file()
	-__str__()
	-_add_header_information_to_cnv_info()
	-_save_file()
	-_save_xml_data_from_cnv()
}

class sensor_info_file.SensorInfoFiles #8E00A6 {
	-_directory
	-_paths
	-_sensor_info_items
==
	+old_write_summary_to_file()
	+write_summary_to_file()
	-_save_info()
}

class sensor_info_item.SensorInfoItem #EA24E3 {
	-_all_columns
	-_calibration_dates
	-_columns
	-_data
	-_key
	-_valid_from
	-_valid_to
	valid_from, @p
	valid_to, @p
==
	+add_data()
	+get_info()
	+get_key(), @sm
	-_add_additional_data()
	-_add_calibration_date()
	-_add_first_data()
	-_add_info()
	-_check_columns()
	-_get_time_object(), @sm
	-_get_time_string(), @sm
	-_set_valid_from()
	-_set_valid_to()
}

class standard_format.CreateStandardFormat #CBFF1A {
	+delivery_metadata_file_path
	+paths
	-_cnv_files
	-_deliverynote_file_path
	-_export_directory
	-_metadata_file_path
	-_metadata_path
	-_output_dir
	-_overwrite
	-_sensorinfo_file_path
==
	+create_files_from_cnv()
	+old_create_delivery_metadata_file()
	-_copy_standard_format_files_to_local()
	-_create_deliverynote_file()
	-_create_metadata_file()
	-_create_sensorinfo_file()
	-_create_standard_format_files()
}

class standard_format.StandardFormatComments #CBFF1A {
	-_automatic_qc
	-_info
	-_path
	info_tags, @p
==
	+get_automatic_qc_datetimes()
	+has_automatic_qc_today()
	+save_comment_info()
	-_automatic_qc_date_from_comment_line(), @sm
	-_automatic_qc_datetime_from_comment_line(), @sm
	-_automatic_qc_matches_today()
	-_save_comment_line()
}

class vis_qc.VisQC #FFD490 {
	+bokeh_app_file_path
	+bokeh_child_process
	+data_directory
	+filters
	+settings_argument_file_path
	+visualize_setting
==
	+start()
	+stop()
	-_create_settings_argument_file()
}

class xmlcon_file.XMLCONfile #79D869 {
	+file_path
	+tree
	serial_number, @p
==
	+get_sensor_info()
	+print_sensors()
}


cnv_column_info.CnvSensorInfo <|-- dict

parent_abc_class.CTDFiles <|-- ABC

file_pattern_nodc.NODCSBECTDFiles <|-- modify.ModifyCTDfiles

file_pattern_old_processing_script.OldSBECTDFiles <|-- modify.ModifyCTDfiles

modify.ModifyCTDfiles <|-- sbe_parent_class.SBECTDFiles

sbe_parent_class.SBECTDFiles <|-- parent_abc_class.CTDFiles

derive.DerivePSAfile <|-- psa_file.PSAfile

loopedit.LoopeditPSAfile <|-- psa_file.PSAfile

psa_file_with_plot.PSAfileWithPlot <|-- psa_file.PSAfile

psa_plot_file.PlotPSAfile <|-- psa_file_with_plot.PSAfileWithPlot

seasave.SeasavePSAfile <|-- psa_file_with_plot.PSAfileWithPlot

cnv_column_info.CnvInfoFile o-- cnv_column_info.CnvSensorInfo

cnv_column_info.CnvInfoFiles o-- cnv_column_info.CnvInfoFile

file_handler.SBEFileHandler o-- file_handler.File
file_handler.SBEFileHandler o-- file_handler.File

metadata.MetadataFile o-- metadata.MetadataRow

standard_format.StandardFormatComments o-- standard_format.StandardFormatComments

cnv_file.CNVfile o-- cnv_column_info.CnvInfoFiles
cnv_file.CNVfile o-- cnv_header.CNVheader
cnv_file.CNVfile o-- cnv_parameter.CNVparameter

standard_format.CreateStandardFormat o-- data_delivery.DeliveryMetadataFile
standard_format.CreateStandardFormat o-- delivery_note.DeliveryNote
standard_format.CreateStandardFormat o-- metadata.MetadataFile
standard_format.CreateStandardFormat o-- sensor_info_file.SensorInfoFiles

modify.ModifyCTDfiles o-- cnv_file.CNVfile

sbe_parent_class.SBECTDFiles o-- cnv_file.CNVfileInfo
sbe_parent_class.SBECTDFiles o-- bl_file.BlFile
sbe_parent_class.SBECTDFiles o-- hdr_file.HdrFile

sbe_processing.SBEProcessing o-- sbe_batch_file.SBEBatchFile
sbe_processing.SBEProcessing o-- sbe_setup_file.SBESetupFile
sbe_processing.SBEProcessing o-- loopedit.LoopeditPSAfile

sbe_setup_file.SBESetupFile o-- psa_plot_file.PlotPSAfile

sensor_info_file.SensorInfoFile o-- param_reported.ParamReported
sensor_info_file.SensorInfoFile o-- cnv_file.CNVfileXML

sensor_info_file.SensorInfoFiles o-- sensor_info_item.SensorInfoItem

param_reported.ParamReported o-- cnv_file.CNVfileXML

@enduml